name: Create Pull Request

on:
  push:
    branches:
      - main  # Branch to trigger the PR creation

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: preti14-m/application
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create --base main --head feature-branch --title "Automated PR" --body "Automated pull request from application repo" --repo preti14-m/LZ-infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
