name: Create PR in LZ-infra

on:
  push:
    branches:
      - main  # Monitor this branch in the application repo

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Generate Branch Name
        id: generate_branch
        run: |
          BRANCH_NAME="update-from-application-$(date +'%Y%m%d-%H%M%S')"
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "::set-output name=branch_name::${BRANCH_NAME}"

      - name: Clone LZ-infra repo
        run: |
          git clone https://github.com/preti14-m/LZ-infra.git lz-infra
          cd lz-infra
          git fetch origin
          BRANCH_NAME="${{ steps.generate_branch.outputs.branch_name }}"
          git checkout -b $BRANCH_NAME

      - name: Set correct permissions for lz-infra
        run: |
          chmod -R 777 lz-infra
          ls -l lz-infra/
          touch value.txt
          chmod 777 value.txt 

      - name: Copy value.txt to LZ-infra
        run: |
          cp value.txt lz-infra/
          ls -d lz-infra/

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd lz-infra
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Automated update from application repository"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/preti14-m/LZ-infra.git
            git push --set-upstream origin $BRANCH_NAME
          fi

      - name: Create Pull Request in LZ-infra
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: preti14-m/LZ-infra  # Target repository for PR
          head: ${{ steps.generate_branch.outputs.branch_name }}  # Source branch for PR
          base: main  # Target branch in LZ-infra for the PR
          title: "Automated PR: Updates from application repo"
          body: "This PR was automatically created by a GitHub Action in the application repository."
