name: Create PR in LZ-infra

on:
  push:
    branches:
      - main  # Replace with the branch you want to monitor

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone LZ-infra repo
        run: |
          git clone https://github.com/preti14-m/LZ-infra.git lz-infra
          cd lz-infra

          # Check out the branch if it exists, otherwise create it
          git checkout -b update-from-application || git checkout update-from-application

      - name: Copy workout.txt to LZ-infra
        run: |
          # Only copy if the file doesn't exist in the destination or is different
          if ! cmp -s value.txt lz-infra/value.txt; then
            touch value.txt; chmod 777 value.txt
            cp value.txt lz-infra/
          else
            echo "File 'value.txt' is already up to date in 'lz-infra'. No need to copy."
          fi

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd lz-infra

          # Check if there are changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            exit 0  # Gracefully exit with success if no changes
          else
            git add .
            git commit -m "Automated update from application repository"
            
            # Push the changes to the remote branch
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/preti14-m/LZ-infra.git
            git push origin update-from-application
          fi

      - name: Create Pull Request in LZ-infra
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: preti14-m/LZ-infra
          head: update-from-application
          base: main  # Change this to the target branch in LZ-infra
          title: "Automated PR: Updates from application repo"
          body: "This PR was automatically created by a GitHub Action in the application repository."
