name: Create PR in LZ-infra 3

on:
  push:
    branches:
      - main  # Monitor this branch in the application repo

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone LZ-infra repo
        run: |
          git clone https://github.com/preti14-m/LZ-infra.git lz-infra
          cd lz-infra

          # Fetch remote branches and create a branch with date
          git fetch origin
          BRANCH_NAME="update-from-application-$(date +'%Y%m%d-%H%M%S')"
          if git rev-parse --verify origin/$BRANCH_NAME; then
            git checkout 1234
          else
            git checkout -b 1234
          fi
          
      - name: Set correct permissions for lz-infra
        run: |
          chmod -R 777 lz-infra
          ls -l lz-infra/
          # Create value.txt if it doesn't exist, and copy it to lz-infra
          touch value.txt
          chmod 777 value.txt 
          
      - name: Copy value.txt to LZ-infra
        run: |
          cp value.txt lz-infra/
          ls -d lz-infra/

      - name: Debug Changes
        run: |
          cd lz-infra
          echo "Checking for changes..."
          git status
          git diff

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd lz-infra

          # Add all changes, including untracked files
          git add -A

          # Check if there are changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            exit 0  # Gracefully exit if no changes are detected
          else
            echo "Changes detected, committing..."
            git commit -m "Automated update from application repository"
            
            # Ensure the remote URL is set correctly with the token
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/preti14-m/LZ-infra.git
            
            # Push the changes and set the upstream branch
            git push --set-upstream origin 1234
          fi

      - name: Create Pull Request in LZ-infra
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: preti14-m/LZ-infra
          head: $BRANCH_NAME
          base: main  # Target branch in LZ-infra for the PR
          title: "Automated PR: Updates from application repo"
          body: "This PR was automatically created by a GitHub Action in the application repository."
